### ISSUE TITLE
Is the server just an example?

### ISSUE THREAD

**Issue by anthonycl** [kjda/ReactJs-Phonegap#8]
I am assuming the server folder contains an example server app that returns some basic stuff the app queries for, such as user information for login etc. If I am correct, what is the app using to communicate? JSON POST? I would want to make the server PHP based, that's why I am inquiring. New to React, thanks for your help!

**Comment by kjda** [comment]
Hi, the server part is actually  doing nothing! It was planned to make some example API but I never managed to find time for it. It will be removed in the next update.

Currently there is no API implemented for communicating with the server, but it is very simple actually. you can create an API module in the util folder using $.ajax for example.. I will include one in the next update which is comming soon
