### ISSUE TITLE
it doesn't work on my macbook air. 

### ISSUE THREAD

**Issue by TonyLuo** [kjda/ReactJs-Phonegap#9]
after I run gulp serve, the chrome popups some message,and then the phonegap connecting to device page  shows all the time

**Comment by qjouda** [comment]
did you run "gulp build-app"?

**Comment by TonyLuo** [comment]
qjouda, thanks a lot. i forgot to run "gulp build-app" -_-|| . after run "gulp build-app", now it works on both pc and macbook. thanks thanks
